"""add record_updated column

Revision ID: 2f5bc2c4aabc
Revises: 4b0459c4643f
Create Date: 2018-08-13 12:02:40.205580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5bc2c4aabc'
down_revision = '4b0459c4643f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('record_updated', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('record_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'record_updated')
    op.drop_column('tweets', 'record_updated')
    # ### end Alembic commands ###
