"""add_new_default

Revision ID: 4b0459c4643f
Revises: db00fa07e026
Create Date: 2018-08-13 11:56:21.448113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0459c4643f'
down_revision = 'db00fa07e026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('record_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('record_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'record_created')
    op.drop_column('tweets', 'record_created')
    # ### end Alembic commands ###
