"""add audit_data columns

Revision ID: d9ac0602d246
Revises: 2f5bc2c4aabc
Create Date: 2018-08-13 12:08:09.631777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ac0602d246'
down_revision = '2f5bc2c4aabc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Used for csun enterprise
    # op.add_column('tweets', sa.Column('audit_data', sa.Text(), nullable=True))
    # op.add_column('users', sa.Column('audit_data', sa.Text(), nullable=True))

    op.add_column('tweets', sa.Column('audit_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('audit_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'audit_data')
    op.drop_column('tweets', 'audit_data')
    # ### end Alembic commands ###
